### ISSUE TITLE
Function directory

### ISSUE THREAD

**Issue by KingofApples** [MemeMayhem/ModExamples#4]
Hi, I posted the issue here https://discord.com/channels/1231086280935473154/1284959553020100692

Like you added a command to pull assets like Characters, Missiles, etc (and thank you for adding this!) could you please do the same for functions?

I am trying to make my attack scale with the Strength attribute. I've dug through every example folder and every instance of damage was hardcoded as a felt value with no attribute scaling. I do not know what function references an attribute, or what function deals with the math for it (if I wanted to do 50% of Strength rather than 100%).

How could I make this attack work, and more importantly, is it possible to get a list of some functions? That way I wouldn't need to flood github with stupid questions like this one. Thank you so much in advance.

**Comment by fx013** [comment]
I haven't found a way to automatically generate an useful list for functions yet. I can generate a function name list, but without argument type info they are not really usable. I'm working with the team to see if we can publish the implementation of some built-in missiles/perks/relics as references. It will take some time because we need to rewrite some code to adapt them to the modding APIs.

Before we have more comprehensive examples/wiki documentation, feel free to post questions here. I'll try to get back to them as soon as I can.

For the specific issue you have, you can use the `caster:GetBoundedAttribute()` API. I have added it to the Basic-NewMissile example: https://github.com/MemeMayhem/ModExamples/commit/2e2ce822225d5526d2e80008b9bb65851484c187

**Comment by KingofApples** [comment]
Thanks for your reply, and for updating the missile example.

I have a few other questions in the meantime I couldn't figure out from the examples:

1. What is the method for adding a stacking effect that does something when it reaches an upper cap? (Like the perk for Flex 66 times to permanently gain 1 strength). The only stacking example I found was gaining 1 strength temporarily when taking damage, uncapped.
2. What is the method for swapping out the artwork on the Ultimate?
3. What is the function for adding permanent attributes on battle finish?
4. What is the function for adding temp attributes on battle start?
5. Is there something similar to caster:GetBoundedAttribute() (which checks attribute values) but instead checks the quantity of a specific Relic or Perk you have?

**Comment by fx013** [comment]
> 1. What is the method for adding a stacking effect that does something when it reaches an upper cap? (Like the perk for Flex 66 times to permanently gain 1 strength). The only stacking example I found was gaining 1 strength temporarily when taking damage, uncapped.

I have added a new example to demonstrate how to do this (partly): https://github.com/MemeMayhem/ModExamples/blob/main/Medium-PerkQuest/additions/scripts/Trigger.lua.txt

It adds 1 rock for every 10 rock hits. Because it uses a custom attribute, it's not displayed in the character attribute UI. We'll add a new mod API to register custom attributes so they can be displayed correctly. Right now I used a debug text bubble to show the progress.

> 2. What is the method for swapping out the artwork on the Ultimate?

There is a Basic-NewUltimate example for this.

> 3. What is the function for adding permanent attributes on battle finish?
> 4. What is the function for adding temp attributes on battle start?

The Medium-PerkQuest example I added above shows how to register callbacks on battle start/end to add health temporarily/permanently.

> 5. Is there something similar to caster:GetBoundedAttribute() (which checks attribute values) but instead checks the quantity of a specific Relic or Perk you have?

They are `caster:HasPerk(name)`, `caster:GetPerkLevel(name)`, `caster:HasRelic(name)` and `caster:GetRelicLevel(name)`.

**Comment by fx013** [comment]
@KingofApples We have added custom attribute support to the mod API. You can use it to display stacking effect progress. This example is updated with custom attribute: https://github.com/MemeMayhem/ModExamples/tree/main/Medium-PerkQuest

There is also a new wiki page listing all API functions of CombatUnit (the type of caster): https://github.com/MemeMayhem/ModExamples/wiki/CombatUnit-Methods . Besides that, we added some game Lua files to this repo for modders to use as references: https://github.com/MemeMayhem/ModExamples/tree/main/References
